title: WachiuSiu
author: Wachiu Siu
description: >-

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

disqus: 
  shortname: wcsiu-github-io

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
